config/routes.rb
RoverTrip::Application.routes.draw do
  root "pages#home"    
  get "home", to: "pages#home", as: "home"
  get "inside", to: "pages#inside", as: "inside"
  
    
  devise_for :users
  
  namespace :admin do
    root "base#index"
    resources :users
    resources :dashboard
    resources :tourisms
  end
  
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/image.rb
class Image < ActiveRecord::Base

  mount_uploader :photo, PhotoUploader

  belongs_to :imageable, polymorphic: true
end

app/models/tourism.rb
class Tourism < ActiveRecord::Base
  has_many :images, as: :imageable, dependent: :destroy
  accepts_nested_attributes_for :images, reject_if: :all_blank, allow_destroy: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Use friendly_id on Users
  extend FriendlyId
  friendly_id :friendify, use: :slugged
  
  # necessary to override friendly_id reserved words
  def friendify
    if username.downcase == "admin"
      "user-#{username}"
    else
      "#{username}"
    end
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  # Pagination
  paginates_per 100
  
  # Validations
  # :username
  validates :username, uniqueness: { case_sensitive: false }
  validates_format_of :username, with: /\A[a-zA-Z0-9]*\z/, on: :create, message: "can only contain letters and digits"
  validates :username, length: { in: 4..10 }
  # :email
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  
  def self.paged(page_number)
    order(admin: :desc, username: :asc).page page_number
  end
  
  def self.search_and_order(search, page_number)
    if search
      where("username LIKE ?", "%#{search.downcase}%").order(
      admin: :desc, username: :asc
      ).page page_number
    else
      order(admin: :desc, username: :asc).page page_number
    end
  end
  
  def self.last_signups(count)
    order(created_at: :desc).limit(count).select("id","username","slug","created_at")
  end
  
  def self.last_signins(count)
    order(last_sign_in_at: 
    :desc).limit(count).select("id","username","slug","last_sign_in_at")
  end
  
  def self.users_count
    where("admin = ? AND locked = ?",false,false).count
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout "admin"
	
  before_filter :require_admin!
  
  def index
    @last_signups = User.last_signups(10)
    @last_signins = User.last_signins(10)
    @count = User.users_count 
  end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
	def index
	end
end

app/controllers/admin/tourisms_controller.rb
class Admin::TourismsController < Admin::BaseController

  def index
  end

  def show
  end

  def new
  	@tourism = Tourism.new
  end

  def edit
  end

  def create
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  before_action :set_user, only: [
    :show,
    :edit,
    :update,
    :destroy
  ]
  

  def index
    @users = User.search_and_order(params[:search], params[:page])
  end
  
  def show
    redirect_to edit_admin_user_path(params[:id])
  end
  
  def edit
  end
  
  def update
    old_username = @user.username
    new_params = user_params.dup
    new_params[:username] = new_params[:username].strip
    new_params[:email] = new_params[:email].strip
    
    @user.username = new_params[:username]
    @user.email = new_params[:email]
    @user.password = new_params[:password] if new_params[:password].strip.length > 0
    @user.password_confirmation = new_params[:password_confirmation] if new_params[:password_confirmation].strip.length > 0
    
    if current_user.id != @user.id
      @user.admin = new_params[:admin]=="0" ? false : true
      @user.locked = new_params[:locked]=="0" ? false : true
    end
    
    if @user.valid?
      @user.skip_reconfirmation!
      @user.save
      redirect_to admin_users_path, notice: "#{@user.username} updated."
    else
      flash[:alert] = "#{old_username} couldn't be updated."
      render :edit
    end
  end
  
  
  private 
  
  def set_user
    @user = User.friendly.find(params[:id])
  rescue
    flash[:alert] = "The user with an id of #{params[:id]} doesn't exist."
    redirect_to admin_users_path
  end
  
  def user_params
    params.require(:user).permit(
    :username,
    :email,
    :password,
    :password_confirmation,
    :admin,
    :locked
    )
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  before_filter :configure_permitted_parameters, if: :devise_controller?
  before_filter :reject_locked!, if: :devise_controller?
  

  # Devise permitted params
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(
      :username, 
      :email, 
      :password, 
      :password_confirmation) 
    }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(
      :username, 
      :email, 
      :password, 
      :password_confirmation,
      :current_password
      ) 
    }
  end
  
  # Redirects on successful sign in
  def after_sign_in_path_for(resource)
    inside_path
  end
  
  # Auto-sign out locked users
  def reject_locked!
    if current_user && current_user.locked?
      sign_out current_user
      user_session = nil
      current_user = nil
      flash[:alert] = "Your account is locked."
      flash[:notice] = nil
      redirect_to root_url
    end
  end
  helper_method :reject_locked!
  
  # Only permits admin users
  def require_admin!
    authenticate_user!
    
    if current_user && !current_user.admin?
      redirect_to root_path
    end
  end
  helper_method :require_admin!
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, only: [
    :inside
  ]

  def home
  end
  
  def inside
  end 
    
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/admin/tourisms_helper.rb
module Admin::TourismsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(value)
    unless value.nil?
      @title = "#{value} | RoverTrip"      
    end
  end
end

app/views/admin/dashboard/index.html.slim
.row
  .col-lg-12
  	.breadcrumb
	  	h1 
	  		i.fa.fa-dashboard.fa-1x 
	  		| Dashboard

app/views/admin/tourisms/_image_fields.html.slim
.nested-fields
  .form-group
    = f.label :photo, class: "col-sm-2 control-label"
    .col-sm-6.custom_file_upload
      = text_field_tag "file_info", nil, class: "file"
      .file_upload
        = f.input :photo, label: false, id: "file_upload"
    = link_to_remove_association "", f

app/views/admin/tourisms/edit.html.erb
<h1>Admin::Tourisms#edit</h1>
<p>Find me in app/views/admin/tourisms/edit.html.erb</p>

app/views/admin/tourisms/index.html.erb
<h1>Admin::Tourisms#index</h1>
<p>Find me in app/views/admin/tourisms/index.html.erb</p>

<%= link_to "new",new_admin_tourism_path, "data-no-turbolink" => true %>

app/views/admin/tourisms/new.html.slim
.row
	h1
		i.fa.fa-plus
		| Tourism New
		small Admin
hr

.col-md-6
  = simple_form_for @tourism, url: admin_tourisms_path,
   defaults: {input_html: {class: "form-horizontal"} }, role: "form" do |f|
  	.form-group
	  	= f.label :name, class: "col-sm-2 control-label", id: :lable_name
	  	.col-sm-10
	  		=f.input :name, input_html: { class: "form-control" }, label: false
  	.form-group
	  	= f.label :country, class: "col-sm-2 control-label"
	  	.col-sm-10
	  		=f.input :country, as: :string, input_html: { class: "form-control" }, label: false
		.form-group
			= f.label :region, class: "col-sm-2 control-label"
			.col-sm-10
				=f.input :region, as: :string, input_html: { class: "form-control" }, label: false
		.form-group
			= f.label :city, class: "col-sm-2 control-label"
			.col-sm-10
				=f.input :city, as: :string, input_html: { class: "form-control" }, label: false
		.form-group
			= f.label :address, class: "col-sm-2 control-label"
			.col-sm-10
				=f.input :address, as: :string, input_html: { class: "form-control" }, label: false
		.form-group
			= f.label :description, class: "col-sm-2 control-label"
			.col-sm-10
				=f.input :description, as: :text, input_html: { class: "form-control" }, label: false
		.form-group
			= f.label :lat, class: "col-sm-2 control-label"
			.col-sm-10
				=f.input :lat, input_html: { class: "form-control" }, label: false
		.form-group
			= f.label :lng, class: "col-sm-2 control-label"
			.col-sm-10
				=f.input :lng, input_html: { class: "form-control" }, label: false
		#images
			= f.simple_fields_for :images, wrapper: 'inline'
	  	.links
	    	= link_to_add_association 'add image', f, :images

.col-md-6
	input#find-location-map.form-control placeholder="Find Location"
	p
		#map-tourism




-content_for :head_stylesheet do
	= stylesheet_link_tag "admin/tourisms"

-content_for :head_javascript do
	= javascript_include_tag "https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&libraries=places"
	= javascript_include_tag "admin/tourisms", "cocoon"

app/views/admin/tourisms/show.html.erb
<h1>Admin::Tourisms#show</h1>
<p>Find me in app/views/admin/tourisms/show.html.erb</p>

app/views/admin/users/edit.html.erb
<div class="row">
  <div class="col-sm-6">
    <h1>
      Edit User <small><%= "#{@user.username.capitalize} - id: #{@user.id}" %></small>
    </h1>
    <p><%= link_to "Back to Users", admin_users_path %></p>

    <%= form_for [:admin, @user], :html => { :role => "form" } do |f| %>
    
    <div class="form-group">
      <%= f.label :username %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.text_field :username, :autofocus => true, class: "form-control" %>  
        </div>
      </div>
    </div>
    
    <div class="form-group">
      <%= f.label :email %>
      <div class="row">
        <div class="col-sm-6">      
          <%= f.email_field :email, class: "form-control" %>  
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password, class: "form-control" %>
        </div>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :password_confirmation %>
      <div class="row">
        <div class="col-sm-6">
          <%= f.password_field :password_confirmation, class: "form-control" %>
        </div>
      </div>
    </div>
    
    <% unless current_user.id == @user.id %>
    <div class="checkbox">
      <%= f.check_box :locked %> <%= f.label :locked, "Is Locked?" %>
    </div>
    
    <div class="checkbox">
      <%= f.check_box :admin %> <%= f.label :admin, "Is Admin?" %>
    </div>    
    <% end %>

    <div class="row">
      <div class="col-sm-6">
        <%= f.submit "Update User", class: "btn btn-danger" %>
      </div>
    </div>    
    
    <% end %>

  </div>
</div>

app/views/admin/users/index.html.erb
<h1>
  <i class="fa fa-user"></i>
  Users <small>Admin</small>
</h1>
<hr></hr>

<%= form_tag admin_users_path, method: 'get', html: {role: "form"} do %>
<p>
  <div class="col-lg-4">
    <%= text_field_tag :search, params[:search], class: "form-control" %>
  </div>

  <div class="col-lg-3">
    <%= submit_tag "Search", :name => nil, class: "btn btn-sm btn-primary" %>
    <%= link_to "All", admin_users_path, {class: "btn btn-sm btn-link"} %>
  </div>
</p>
<% end %>

<br/>
<br/>
<br/>


<table class="table table-striped">
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Admin</th>
    <th>Email</th>
    <th>Sign In Count</th>
    <th></th>
  </tr>
  
  <% @users.each do |user| %>
  
  <tr>
    <td><%= user.id %></td>
    <td><%= link_to user.username.capitalize, admin_user_path(user) %></td>
    <td><%= user.admin? ? "<b>yes</b>".html_safe : "no" %></td>
    <td><%= user.email %></td>
    <td><%= user.sign_in_count %></td>
    <td>
      <%= link_to admin_user_path(user), class: "btn btn-primary" do %>
        <i class= "fa fa-pencil"></i>
        Edit
      <%end%>
    </td>
  </tr>
  
  <% end %>
  
</table>

<div class="text-center">
  <p><%= page_entries_info @users %></p>
  <%= paginate @users %>
</div>

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    
    <div class="row footer-first-row">
      
      <div class="col-xs-12 text-center">
        <p><small>
          &copy; 2014 - Yourself!
          <br/>
          Assembled with <%= link_to "RailsBricks", "http://www.railsbricks.net" %>
        </small></p>
      </div>
      
    </div>
    
  </div>
</div>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<% if !user_signed_in? %>
<li><%= link_to "Sign in", new_user_session_path %></li>
<li><%= link_to "Sign up", new_user_registration_path %></li>
<% else %>
<li><%= link_to "Protected Page", inside_path %></li>
<li><%= link_to "Edit your account", edit_user_registration_path %></li>

<% if current_user.admin? %>
<li><%= link_to "Admin", admin_root_path %></li>
<% end %>

<li><%= link_to "Sign out", destroy_user_session_path, data:{method: :delete} %></li>
<% end %>

app/views/layouts/admin.html.slim
doctype
html
  head
    meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport"
      title= @title || "RoverTrip"
      = favicon_link_tag 'favicon.ico'
      = stylesheet_link_tag "application", "sb-admin", media: "all", "data-turbolinks-track" => true
      = yield :head_stylesheet
      = csrf_meta_tags
  body
    #wrapper
      header
        = render 'layouts/admin/navigation'
      #page-wrapper
        = yield
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = yield :head_javascript

app/views/layouts/admin/_navigation.html.slim
nav.navbar.navbar-inverse.navbar-fixed-top role="navigation"
  .navbar-header
    button.navbar-toggle data-target=".navbar-ex1-collapse" data-toggle="collapse" type="button"
      span.sr-only Toggle navigation
      span.icon-bar
      span.icon-bar
      span.icon-bar
    a.navbar-brand href="index.html" SB Admin

  / menu admin
  .collapse.navbar-collapse.navbar-ex1-collapse
  	ul.nav.navbar-nav.side-nav
		  li.active
		    = link_to admin_root_path do 
		      i.fa.fa-dashboard
		      | Dashboard
		  li
		    = link_to admin_users_path do
		      i.fa.fa-user
		      | User
		  li
		  	= link_to admin_tourisms_path do
		      i.fa.fa-camera
		      | Tourisms
		  li
		    a href="forms.html"
		      i.fa.fa-edit
		      | Forms
		  li
		    a href="typography.html"
		      i.fa.fa-font
		      | Typography
		  li
		    a href="bootstrap-elements.html"
		      i.fa.fa-desktop
		      | Bootstrap Elements
		  li
		    a href="bootstrap-grid.html"
		      i.fa.fa-wrench
		      | Bootstrap Grid
		  li
		    a href="blank-page.html"
		      i.fa.fa-file
		      | Blank Page

  	ul.nav.navbar-nav.navbar-right.navbar-user
  		li.dropdown
  			a href="#"
				  i.fa.fa-envelope
				  | Messages
			li.dropdown
				= link_to destroy_user_session_path, data:{method: :delete} do
					i.fa.fa-power-off
					| Log Out

					  



			

		
				  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title><%= @title || "RoverTrip" %></title>
  <%= favicon_link_tag 'favicon.ico' %>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="wrap">
    <header>
      <%= render 'layouts/navigation' %>
    </header>
      
    <div class="container">
       
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3 text-center">
          <%= render 'layouts/messages' %>
        </div>
      </div>
      
      <div class="row">
        <div class="col-sm-12">
          <%= yield %>
        </div>     
      </div>  
      
    </div>
  </div>
    
  <%= render 'layouts/footer' %>    

</body>
</html>

app/views/pages/home.html.erb
<% title("Home Page") %>
<h1>Home Page <small>views/pages/home.html.erb</small></h1>
<p>This is your home page. Use the menu at the top to sign in / sign up / sign out.</p>

app/views/pages/inside.html.erb
<h1>Protected Page</h1>
<p>This page is only visible to signed in users. Edit it at: <em>views/pages/inside</em></p>
<p>You can change the page users see after successfully signing in within the method <em>after_sign_in_path_for</em> inside <strong>application_controller.rb</strong></p>